#!/usr/bin/env python3
"""Build the Electromagnetics lecture notes (Persian and English editions).

Layout (one folder per chapter, languages inside):
  NN-slug/{fa,en}/moduleNN-slug.md        source (Markdown + $maths$), transcribed from the
                                          instructor's notes in source/ — the only authority
  NN-slug/{fa,en}/content.tex             generated body
  NN-slug/{fa,en}/moduleNN-slug.tex       standalone chapter  -> .pdf
  00-full-notes/{fa,en}/                  the complete book
  template/figures/<name>.tex             drawings (```{.figure #name} in the sources)
  template/motifs/mNN.tex                 the motif of chapter NN's opening page
  specimen/{fa,en}/specimen.md            typesetting specimen of the design system (QA only)

Usage:  python3 tools/build.py [--no-pdf] [--only fa|en] [--chapter 05] [--book-only] [--specimen]
Needs:  pandoc >= 3, XeLaTeX + latexmk, TeX Gyre Termes / Heros / Termes Math.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FILTER = ROOT / "tools" / "md2tex.lua"
PANDOC_FROM = "markdown+fenced_divs-auto_identifiers-implicit_figures-superscript-subscript-strikeout"
FA_DIGITS = str.maketrans("0123456789", "۰۱۲۳۴۵۶۷۸۹")
BOOK = "Electromagnetics"

# Parts of the book, only if the instructor's material is divided into parts:
#   (key, {"fa": numeral, "en": numeral}, {"fa": title, "en": title}, first chapter, last chapter)
PARTS = []


def md_title(md: Path):
    for line in md.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return md.stem


_INLINE = {}


def filter_env(lang):
    return dict(os.environ, EL_LANG=lang, EL_FIGDIR=str(ROOT / "template" / "figures"))


def inline_tex(text: str, lang: str) -> str:
    """A title rendered by the filter (inline maths, Latin runs in Persian)."""
    key = (text, lang)
    if key not in _INLINE:
        tex = subprocess.run(
            ["pandoc", "-f", PANDOC_FROM, "-t", "latex", "--wrap=none", "--lua-filter", str(FILTER)],
            input=text, check=True, capture_output=True, text=True, env=filter_env(lang)).stdout
        _INLINE[key] = tex.strip()
    return _INLINE[key]


def pandoc_body(md: Path, lang: str) -> str:
    tex = subprocess.run(
        ["pandoc", "-f", PANDOC_FROM, "-t", "latex", "--wrap=preserve", "--lua-filter", str(FILTER), str(md)],
        check=True, capture_output=True, text=True, env=filter_env(lang)).stdout
    return postprocess(tex)


def postprocess(tex: str) -> str:
    """Tables: centred, in the house style, short ones never split."""
    tex = tex.replace("\\begin{longtable}[]", "\\begin{longtable}[c]")
    tex = tex.replace("\\toprule\\noalign{}\n", "\\toprule\\noalign{}\n\\ELtablehead ")

    def keep(m):
        # rules as wide as the tinted head row: no @{} trimming of the outer column padding
        t = re.sub(r"(\\begin\{longtable\}\[c\]\{)@\{\}(.*?)@\{\}\}", r"\1\2}", m.group(0), count=1)
        rows = t.count("\\\\\n")
        need = min(int(rows * 1.8) + 3, 22)
        body = t.replace("\\\\\n", "\\\\\\noalign{\\vskip 4pt}\n")
        return f"\\Needspace{{{need}\\baselineskip}}\n" + body
    return re.sub(r"\\begin\{longtable\}.*?\\end\{longtable\}", keep, tex, flags=re.S)


def section_list(body: str):
    out = []
    for line in body.splitlines():
        m = re.match(r"\\ELsection\{(.*)\}\{[^{}]*\}\s*$", line)
        if m:
            out.append(m.group(1))
    return out


def minitoc(titles):
    items = "".join(f"\\ELtocitem{{{i}}}{{{t}}}\n" for i, t in enumerate(titles, 1))
    return f"\\begin{{ELminitoc}}\n{items}\\end{{ELminitoc}}\n"


def main_file(lang, preamble_extra, body, what="lecture notes"):
    return (
        "% !TEX program = xelatex\n"
        f"% Electromagnetics — {what} ({'Persian' if lang == 'fa' else 'English'}). Generated by tools/build.py.\n"
        "\\documentclass[11pt]{article}\n"
        "\\def\\ELroot{../../template}\n"
        f"\\input{{\\ELroot/el-{lang}}}\n"
        f"{preamble_extra}"
        "\\begin{document}\n"
        f"{body}"
        "\\end{document}\n")


def num(n, lang):
    return str(n).translate(FA_DIGITS) if lang == "fa" else str(n)


def chapter_dirs():
    for topic in sorted(ROOT.glob("[0-9][0-9]-*")):
        n, slug = topic.name.split("-", 1)
        if n != "00":
            yield int(n), n, slug, topic


def chapter_block(n, title, other_title, secs, inp):
    # the page break comes first, so that the last page of the previous chapter keeps its own head
    return (f"\\clearpage\n\\ELsetmodule{{{n}}}{{{title}}}{{{other_title}}}\n"
            f"\\ELchapterpage{{{n}}}{{{n}}}{{{title}}}{{{other_title}}}\n"
            f"{minitoc(secs)}\\ELchapterend\n\\input{{{inp}}}\n")


def book_front(lang, chapters):
    parts = ["\\pagenumbering{roman}\\setcounter{page}{1}\n\\ELcoverpage\n\\ELtitlepage\n"]
    toc = ["\\ELsetmodule{0}{\\ELlangContents}{}\n\\begin{ELbooktoc}\n"]
    groups = PARTS or [(None, None, None, min(chapters, default=1), max(chapters, default=0))]
    for pk, pnum, ptitle, lo, hi in groups:
        if pk:
            toc.append(f"\\ELtocpart{{{pnum[lang]}}}{{{ptitle[lang]}}}\n")
        for n in range(lo, hi + 1):
            if n not in chapters:
                continue
            title, _, _, secs = chapters[n]
            toc.append(f"\\ELtocchapter{{{n}}}{{{num(n, lang)}}}{{{title}}}\n")
            for i, t in enumerate(secs, 1):
                toc.append(f"\\ELtocitemk{{{n}}}{{{i}}}{{{num(n, lang)}.{num(i, lang)}}}{{{t}}}\n")
    toc.append("\\end{ELbooktoc}\n")
    parts.append("".join(toc))
    parts.append("\\clearpage\\pagenumbering{arabic}\\setcounter{page}{1}\n")
    return parts, groups


def build_sources(lang, only=None, book_only=False):
    other = "en" if lang == "fa" else "fa"
    texs, chapters = [], {}
    for n, nn, slug, topic in chapter_dirs():
        md = topic / lang / f"module{nn}-{slug}.md"
        if not md.exists():
            continue
        title = inline_tex(md_title(md), lang)
        other_md = topic / other / md.name
        other_title = inline_tex(md_title(other_md), other) if other_md.exists() else ""
        folder = md.parent
        skip = book_only or bool(only and nn != only)
        if skip and (folder / "content.tex").exists():
            body = (folder / "content.tex").read_text(encoding="utf-8")
        else:
            body = pandoc_body(md, lang)
            (folder / "content.tex").write_text(body, encoding="utf-8")
        secs = section_list(body)
        chapters[n] = (title, other_title, folder, secs)
        if skip:
            continue
        (folder / f"{md.stem}.tex").write_text(main_file(
            lang, f"\\ELsetmodule{{{n}}}{{{title}}}{{{other_title}}}\n",
            f"\\ELchapterpage{{{n}}}{{{n}}}{{{title}}}{{{other_title}}}\n"
            f"{minitoc(secs)}\\ELchapterend\n\\input{{content}}\n"), encoding="utf-8")
        texs.append(folder / f"{md.stem}.tex")

    if not only and chapters:
        folder = ROOT / "00-full-notes" / lang
        folder.mkdir(parents=True, exist_ok=True)
        parts, groups = book_front(lang, chapters)
        for pk, pnum, ptitle, lo, hi in groups:
            if pk:
                rng = (f"فصل‌های {num(lo, lang)} تا {num(hi, lang)}" if lang == "fa" else f"Chapters {lo}--{hi}")
                parts.append(f"\\ELpartpage{{{pk}}}{{{pnum[lang]}}}{{{ptitle[lang]}}}{{{ptitle[other]}}}{{{rng}}}\n")
            for n in range(lo, hi + 1):
                if n not in chapters:
                    continue
                title, other_title, cfolder, secs = chapters[n]
                rel = cfolder.relative_to(ROOT).as_posix()
                parts.append(chapter_block(n, title, other_title, secs, f"../../{rel}/content"))
        name = f"{BOOK}-{lang}"
        (folder / f"{name}.tex").write_text(main_file(lang, "", "".join(parts)), encoding="utf-8")
        texs.append(folder / f"{name}.tex")
    return texs


def build_specimen(lang):
    """The design specimen: cover, title page, contents, one opening page and every block type.
    Its text is a neutral typesetting sample, not course content, and it is never part of the book."""
    other = "en" if lang == "fa" else "fa"
    folder = ROOT / "specimen" / lang
    md = folder / "specimen.md"
    title = inline_tex(md_title(md), lang)
    other_title = inline_tex(md_title(ROOT / "specimen" / other / "specimen.md"), other)
    body = pandoc_body(md, lang)
    (folder / "content.tex").write_text(body, encoding="utf-8")
    secs = section_list(body)
    parts, _ = book_front(lang, {1: (title, other_title, folder, secs)})
    parts.append(chapter_block(1, title, other_title, secs, "content"))
    tex = folder / f"specimen-{lang}.tex"
    tex.write_text(main_file(lang, "", "".join(parts), "design specimen"), encoding="utf-8")
    return [tex]


def compile_tex(tex: Path):
    cmd = ["latexmk", "-xelatex", "-interaction=nonstopmode", "-halt-on-error", tex.name]
    r = subprocess.run(cmd, cwd=tex.parent, capture_output=True, text=True)
    log = tex.with_suffix(".log")
    missing, overfull, undef = set(), 0, 0
    if log.exists():
        text = log.read_text(errors="replace")
        missing = set(re.findall(r"Missing character: There is no (.) ", text))
        big = [float(x) for x in re.findall(r"^Overfull \\hbox \((\d+\.\d+)pt", text, flags=re.M)]
        overfull = sum(1 for x in big if x > 2.0)
        undef = len(re.findall(r"Reference `[^']*' on page \d+ undefined", text))
    status = "ok" if r.returncode == 0 else "FAILED"
    msg = f"[{status}] {tex.relative_to(ROOT)}"
    if overfull:
        msg += f"  overfull>2pt: {overfull}"
    if undef:
        msg += f"  undefined refs: {undef}"
    if missing:
        msg += f"  missing glyphs: {''.join(sorted(missing))}"
    if r.returncode != 0:
        msg += "\n" + (r.stderr + r.stdout)[-3000:]
    return r.returncode == 0, msg


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-pdf", action="store_true", help="generate the .tex files only")
    ap.add_argument("--only", choices=["fa", "en"], help="one language")
    ap.add_argument("--chapter", help="one chapter, e.g. 05 (the book is not rebuilt)")
    ap.add_argument("--book-only", action="store_true", help="only the complete book")
    ap.add_argument("--specimen", action="store_true", help="only the design specimen")
    ap.add_argument("--jobs", type=int, default=4)
    a = ap.parse_args()
    if not shutil.which("pandoc") or not shutil.which("latexmk"):
        sys.exit("needs pandoc and latexmk (XeLaTeX)")
    texs = []
    for lang in ([a.only] if a.only else ["fa", "en"]):
        texs += build_specimen(lang) if a.specimen else build_sources(lang, a.chapter, a.book_only)
    print(f"generated {len(texs)} LaTeX files")
    if not texs and not a.specimen:
        print("no chapter sources yet (NN-slug/{fa,en}/moduleNN-slug.md); try --specimen")
    if a.no_pdf:
        return
    ok = True
    with ThreadPoolExecutor(a.jobs) as ex:
        for good, msg in ex.map(compile_tex, texs):
            ok &= good
            print(msg, flush=True)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
