#!/usr/bin/env python3
"""Generate the data-driven figures (computed curves written as TikZ coordinates).

  m02-ex8-field.tex   field lines and equipotentials of the two charges +q, -q of example 2-8
                      (Ch2_4, slide 11)

Usage: python3 tools/genfigs.py
"""
import math
from pathlib import Path

FIG = Path(__file__).resolve().parent.parent / "template" / "figures"
QP, QM = (0.0, 1.0), (0.0, -1.0)          # +q above, -q below (as on the slide)
BOX = (-3.4, 3.4, -3.0, 3.0)


def field(x, y):
    ex = ey = 0.0
    for (cx, cy), s in ((QP, 1.0), (QM, -1.0)):
        dx, dy = x - cx, y - cy
        r3 = (dx * dx + dy * dy) ** 1.5
        ex += s * dx / r3
        ey += s * dy / r3
    return ex, ey


def trace(x, y, perp=False, step=0.01, nmax=4000, closed=False):
    pts = [(x, y)]
    x0, y0 = x, y
    for n in range(nmax):
        ex, ey = field(x, y)
        if perp:
            ex, ey = -ey, ex
        m = math.hypot(ex, ey)
        x, y = x + step * ex / m, y + step * ey / m
        pts.append((x, y))
        if not (BOX[0] <= x <= BOX[1] and BOX[2] <= y <= BOX[3]):
            break
        if math.hypot(x - QM[0], y - QM[1]) < 0.12:
            break
        if closed and n > 50 and math.hypot(x - x0, y - y0) < 1.5 * step:
            pts.append((x0, y0))
            break
    return pts


def potential(x, y):
    return sum(s / math.hypot(x - cx, y - cy) for (cx, cy), s in ((QP, 1.0), (QM, -1.0)))


def equipotential(y0, n=180):
    """The closed equipotential about +q through (0, y0): on each ray from +q the radius where
    V equals V(0, y0), found by bisection."""
    c = potential(0.0, y0)
    pts = []
    for k in range(n + 1):
        t = 2 * math.pi * k / n
        lo, hi = 1e-3, 6.0
        for _ in range(60):
            mid = 0.5 * (lo + hi)
            if potential(QP[0] + mid * math.sin(t), QP[1] + mid * math.cos(t)) > c:
                lo = mid
            else:
                hi = mid
        pts.append((QP[0] + lo * math.sin(t), QP[1] + lo * math.cos(t)))
    return pts


def path(pts, every=4):
    sel = pts[::every] + [pts[-1]]
    return " ".join(f"({x:.3f},{y:.3f})" for x, y in sel)


def ex8():
    out = ["% Ch2_4, slide 11 (example 2-8): field lines (solid, with arrows) and equipotentials",
           "% (red, dashed) of the charges +q and -q.  Generated by tools/genfigs.py.",
           "\\begin{tikzpicture}[scale=0.95]",
           "  \\clip (-3.45,-3.05) rectangle (3.45,3.05);"]
    for a in range(10, 360, 20):
        t = math.radians(a)
        pts = trace(QP[0] + 0.12 * math.sin(t), QP[1] + 0.12 * math.cos(t))
        out.append(f"  \\draw[ELcField,line width=0.7pt,ELmid] plot coordinates{{{path(pts)}}};")
        # the mirror image: lines that end on -q, drawn from below
        mp = [(x, -y) for x, y in pts]
        if math.hypot(pts[-1][0] - QM[0], pts[-1][1] - QM[1]) > 0.2:   # the line left the picture
            out.append(f"  \\draw[ELcField,line width=0.7pt,ELmid] plot coordinates{{{path(list(reversed(mp)))}}};")
    for y0 in (1.35, 1.75, 2.35):
        pts = equipotential(y0)
        out.append(f"  \\draw[ELcSource,dashed,line width=0.6pt] plot coordinates{{{path(pts, 2)}}};")
        out.append(f"  \\draw[ELcSource,dashed,line width=0.6pt] plot coordinates{{{path([(x, -y) for x, y in pts], 2)}}};")
    out.append("  \\draw[ELcSource,dashed,line width=0.6pt] (-3.4,0)--(3.4,0);")
    for (cx, cy), s in ((QP, "+"), (QM, "-")):
        out.append(f"  \\draw[ELink,line width=0.8pt,fill=white] ({cx},{cy}) circle (0.17) node[font=\\bfseries\\small]{{${s}$}};")
    out.append("\\end{tikzpicture}")
    (FIG / "m02-ex8-field.tex").write_text("\n".join(out) + "\n", encoding="utf-8")


if __name__ == "__main__":
    ex8()
    print("written:", FIG / "m02-ex8-field.tex")
